[global]
support = ["testcase", "./correct/taiko.h", "./dummy/hw0101.c", "./dummy/hw0102.c", "./dummy/hw0103.c", "./dummy/hw0104.c"]

[[case]]
name = "case1"
command = "./hw0105 < testcase/case1.tja > case1.txt; ./hw0105 < testcase/case1LF.tja > case1LF.txt"

[[case]]
name = "case2"
command = "./hw0105 < testcase/case2.tja > case2.txt; ./hw0105 < testcase/case2LF.tja > case2LF.txt"

[[case]]
name = "case3"
command = "./hw0105 < testcase/case3.tja > case3.txt; ./hw0105 < testcase/case3LF.tja > case3LF.txt"

[[case]]
name = "case4"
command = "./hw0105 < testcase/case4.tja > case4.txt; ./hw0105 < testcase/case4LF.tja > case4LF.txt"

[[case]]
name = "case5"
command = "./hw0105 < testcase/case5.tja > case5.txt; ./hw0105 < testcase/case5LF.tja > case5LF.txt"

[[case]]
name = "case6"
command = "./hw0105 < testcase/case6.tja > case6.txt; ./hw0105 < testcase/case6LF.tja > case6LF.txt"