[package]
name = "student_grader"
version = "0.1.0"
edition = "2021"


authors = ["Your Name <your.email@example.com>"]
description = "A command line tool to grade student assignments"
license = "MIT"

[dependencies]
regex = "1.11.1"  
zip = "2.2.0"
