[global]
homework = "MID"
testcase = 0
dependent = [] 
# example: dependent = ["mid03.c", "test.png",]   

[testcase01]
testcase = 0

[testcase02]
testcase = 0

[testcase03]
testcase = 20

[testcase04]
testcase = 20

[testcase05]
testcase = 20
