[global]
command = "./mid03"
support = ["./support/maldives.bmp", "./support/maldives_gray.bmp", "./support/480-360-sample.bmp"]

[[case]]
name = "case1"
file = "./testcase/1.in"
pts = 5

[[case]]
name = "case2"
file = "./testcase/2.in"
pts = 5

[[case]]
name = "case3"
file = "./testcase/3.in"
pts = 5

[[case]]
name = "case4"
file = "./testcase/4.in"
pts = 5

[[case]]
name = "case5"
file = "./testcase/5.in"
pts = 5