[global]
support = ["support/fin03.c", "support/database.h"]
command = "./fin03"

[[case]]
name = "case1"
file = "testcase/1.in"
correct = "correct/output1.txt"
pts = 8

[[case]]
name = "case2"
file = "testcase/2.in"
correct = "correct/output2.txt"
pts = 8

[[case]]
name = "case3"
file = "testcase/3.in"
correct = "correct/output3.txt"
pts = 8

[[case]]
name = "case4"
file = "testcase/4.in"
correct = "correct/output4.txt"
pts = 8

[[case]]
name = "case5"
file = "testcase/5.in"
correct = "correct/output5.txt"
pts = 8