[global]
support = ["./support/tas.h", "./support/hw0505.c", "./support/empty.c", "./support/mutiple.c"]

[[case]]
name = "case1"
correct = "./correct/case1.txt"
pts = 2.5
command = "./hw0302 -i tas.h hw0505.c"

[[case]]
name = "case2"
correct = "./correct/case2.txt"
pts = 2.5
command = "./hw0302 -i tas.h --linum -c hw0505.c"

[[case]]
name = "case3"
correct = "./correct/case3.txt"
pts = 2.5
command = "./hw0302 -i tas.h --code hw0505.c"

[[case]]
name = "case4"
correct = "./correct/case4.txt"
pts = 2.5
command = "./hw0302 -f button_set_frame -l hw0505.c"

[[case]]
name = "case5"
correct = "./correct/case5.txt"
pts = 2.5
command = "./hw0302 --help -i tas.h -l -c hw0505.c"

[[case]]
name = "case6"
correct = "./correct/case6.txt"
pts = 2.5
command = "./hw0302 -a -b -c -d -e -f hi hw0505.c"

[[case]]
name = "case7"
correct = "./correct/case7.txt"
pts = 2.5
command = "./hw0302 -i tas.h -l -c hw0505.c empty.c"

[[case]]
name = "case8"
correct = "./correct/case8.txt"
pts = 2.5
command = "./hw0302 -i tas.h -l -c hw0505.c empty.c mutiple.c"