[global]
command = "./hw0204"
correct = "./correct/hw0204.c"

[[case]]
name = "case1"
file = "./testcase/1.in"
pts = 4

[[case]]
name = "case2"
file = "./testcase/2.in"
pts = 2

[[case]]
name = "case3"
file = "./testcase/3.in"
pts = 2

[[case]]
name = "case4"
file = "./testcase/4.in"
pts = 2

[[case]]
name = "case5"
file = "./testcase/5.in"
pts = 2

[[case]]
name = "case6"
file = "./testcase/6.in"
pts = 4

[[case]]
name = "case7"
file = "./testcase/7.in"
pts = 4